# Generated by Django 5.1.6 on 2025-02-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_user_is_staff_remove_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
