# Generated by Django 5.1.6 on 2025-02-12 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_user_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='collaborators',
            new_name='active_collaborators',
        ),
    ]
