# Generated by Django 5.1.6 on 2025-02-12 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_collaborator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='active_collaborators',
        ),
    ]
